CREATE
DATABASE IF NOT EXISTS HELPCAR;


CREATE TABLE IF NOT EXISTS CADASTRO
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    NOME          VARCHAR(255) NOT NULL,
    GENERO        VARCHAR(10),
    SOBRENOME     VARCHAR(255) NOT NULL,
    CPF           VARCHAR(14) NOT NULL,
    DT_NASCIMENTO DATE,
    PCD           BOOLEAN
);

CREATE TABLE IF NOT EXISTS LOGIN
(
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CORRESPONDENCIA
(
    ESTADO      VARCHAR(255),
    CIDADE      VARCHAR(255),
    BAIRRO      VARCHAR(255),
    NUMERO      VARCHAR(20),
    ENDERECO    VARCHAR(255),
    COMPLEMENTO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PAGAMENTO
(
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    NUM_CARTAO    VARCHAR(20) NOT NULL,
    DT_EXPIRACAO  DATE NOT NULL,
    CVV           VARCHAR(4) NOT NULL
);
